### ISSUE TITLE
dot product example doesn't really compute n! 

### ISSUE THREAD

**Issue by aguaviva** [espressif/esp-dsp#1]
The dot product in the esp-dsp/examples/dotprod/main/dsps_dotproduct_main.c file won't compute n! as the comment says, it will just compute the addition of all numbers from 0 to 255.

**Comment by dmitry1945** [comment]
Sure!
It compute sum!

**Comment by igrr** [comment]
Fixed in https://github.com/espressif/esp-dsp/commit/2a490f4908102b0809fe95e56551826599365936.

**Comment by aguaviva** [comment]
great! And sorry for being over pedantic :)
