### ISSUE TITLE
How do I run the test suite?

### ISSUE THREAD

**Issue by brianbienvenu** [espressif/esp-dsp#16]
I tried to compile and run the "test_app" included here, however it just says:
```
Here's the test menu, pick your combo:

Enter test for running.
```
I enter a number, and get:
```
-----------------------
0 Tests 0 Failures 0 Ignored
OK
Enter next test, or 'enter' to see menu
```

I guess that the files in the test_app folder don't like up with the test suite correctly, how do I make it work?

**Comment by dmitry1945** [comment]
I think now you have place esp-dsp to the `esp-edf/components/esp-dsp` folder. But for tests, you have to place esp-dsp to the `esp-edf/components/dsp` folder. Just rename it.
Then in two files you will need to removw lines `#include "fft.h"` (this is bug. A bugfix will come soon).

Regards,
Dmitry

**Comment by dmitry1945** [comment]
@brianbienvenu just rename filder. 
The headers I've removed.

Regards,
Dmitry

**Comment by brianbienvenu** [comment]
Thanks, it works after changing the folder name, and with your new commit.

Should "how to run the tests" instructions be added to the repo readme, or should this have been obvious to me?

**Comment by dmitry1945** [comment]
"How to run the tests" is the standard procedure for the esp-idf and it's described there. Or you mean something else?
I will add to read.me description with renaming.

Regards,
Dmitry

**Comment by brianbienvenu** [comment]
Thanks, no worries. I'm not an esp-idf expert yet!
