### ISSUE TITLE
Compilation error in fft4real example for ANSI DSP optimization configuration.

### ISSUE THREAD

**Issue by Vvard** [espressif/esp-dsp#24]
I tested fft4real example for ANSI DSP optimization but got below compile error.

![ESP2Optimized2ANSI](https://user-images.githubusercontent.com/54348801/108192240-77a98f00-712d-11eb-97e0-9ffc0628d742.png)

Error:
C:/esp-dsp/modules/fft/include/dsps_fft4r.h:157:29: error: implicit declaration of function 'dsps_bit_rev4r_fc32_ansi'; did you mean 'dsps_bit_rev_fc32_ansi'? [-Werror=implicit-function-declaration]

**Comment by Vvard** [comment]
Hi team,
Just wanted to know if you had a look into this issue?

Additional info: There is no dsps_fft4r_fc32_ansi function declaration in the code
https://github.com/espressif/esp-dsp/blob/master/modules/fft/include/dsps_fft4r.h#L168

**Comment by dmitry1945** [comment]
Hi @Vvard 
I will fix it today.
The new version will be available soon.

Thank you very much,
Dmitry

**Comment by Vvard** [comment]
Hi @dmitry1945,
Thanks a lot, I will wait for the new version)

Regards,
Vard
