### ISSUE TITLE
ESP-DSP optimized functions can't be found during linking(IDFGH-5484)

### ISSUE THREAD

**Issue by ahmedwahdan** [espressif/esp-dsp#31]
## Environment

- Development Kit:     ESP32-DevKitC
Module or chip used:  ESP32-WROOM-32
- IDF version  4.2
- Build System:         idf.py
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     WindowsPlain Command Prompt
- Using an IDE?: No|
- Power Supply:         USB

## Problem Description

After adding ESP-DSP component to esp-idf components, only ANSI C function can be compiled, the optimized functions couldn't be found

![image](https://user-images.githubusercontent.com/5406736/124352500-b7ff3a80-dc00-11eb-877c-448e53ca81eb.png)

### Expected Behavior
Be able to use optimized DSP functions
### Steps to reproduce

1. Clone DSP component to idf components
2. configure the DSP to use optimized functions

![image](https://user-images.githubusercontent.com/5406736/124255155-27eec180-db2a-11eb-9ffc-4009fe9d7016.png)

3. Build any DSP example

Build output:
[build_output.txt](https://github.com/espressif/esp-idf/files/6758288/build_output.txt)

**Comment by igrr** [comment]
Sorry for the late response @ahmedwahdan, it is a bug we introduced in https://github.com/espressif/esp-dsp/commit/901d03f4f92e0661564598f3b9e939c678481d7c. CONFIG_IDF_TARGET_ARCH_XTENSA is not defined in IDF 4.2.x, and was only added in IDF 4.3.

**Comment by ahmedwahdan** [comment]
No problem, What about the V3.3, it seems that the sdkconfig.h is included from different path which doesn't include CONFIG_IDF_TARGET_ARCH_XTENSA

**Comment by igrr** [comment]
Yes, it's the same for v3.3, CONFIG_IDF_TARGET_ARCH_XTENSA is not defined there.
This issue in esp-dsp happens with every IDF version older than v4.3.
