### ISSUE TITLE
建议增加更多的矩阵运算函数  (DSP-84)

### ISSUE THREAD

**Issue by ou2356** [espressif/esp-dsp#40]
在你们的esp-drone开源项目中用到的矩阵求逆和矩阵转置函数都是从arm的dsp库移植过来的，然而在你们的官方的dsp库没有这两个功能函数，非常希望用到你们官方自己出的矩阵运算函数。

**Comment by dmitry1945** [comment]
Hi @ou2356 ,
You can use inverse() (or pinv()) to inverse matrix, and t() to transpose. 
Or you mean something else?

**Comment by ou2356** [comment]
> Hi @ou2356 , You can use inverse() (or pinv()) to inverse matrix, and t() to transpose. Or you mean something else?

Hi@[dmitry1945](https://github.com/dmitry1945),
Thank you for your reminder. I'm at mat H and mat CPP found the implementation of the code you said. They are written in C + +, so I didn't find it when I first saw it. Thank you very much.
