### ISSUE TITLE
Is dsps_fir_f32_aes3 implementation working?  (DSP-92)

### ISSUE THREAD

**Issue by AristarchosOfSamos** [espressif/esp-dsp#55]
Hi,

Trying to utilize FIR on a ESP32S3 (ESP32-S3-DevKitC-1) and seen the esp-dsp FIR implementation file here
[https://github.com/espressif/esp-dsp/blob/master/modules/fir/float/dsps_fir_f32_aes3.S](https://github.com/espressif/esp-dsp/blob/master/modules/fir/float/dsps_fir_f32_aes3.S)

Tried a test of my own (based on test_app) and its functionality show FAIL whereas its result is different from the standard ansi result.

Is there any example/test that we can do for ESP32S3 on esp-dsp FIR?
Is this implementation file working correctly?

Regards,

/Edit
Also seen this issue, but do not know its status
[https://github.com/espressif/esp-dsp/issues/44#issue-1203590908](https://github.com/espressif/esp-dsp/issues/44#issue-1203590908)

**Comment by dmitry1945** [comment]
Hi @AristarchosOfSamos ,
FIR for floating point is not working now. 
Will fix soon.
For now, please use esp32 or ansi version.

Regards,
Dmitry

**Comment by herculanodavi** [comment]
Hello,

do we have any news on this functionality?

**Comment by dmitry1945** [comment]
Hi @herculanodavi 
I'ts in progress.
Will come soon.

**Comment by dmitry1945** [comment]
@herculanodavi  it's working. I will close the issue.

Thank you very much,
Dmitry
