### ISSUE TITLE
could you add support for basic fast sin-cos function set to speed-up math calc  (DSP-88)

### ISSUE THREAD

**Issue by wanckl** [espressif/esp-dsp#57]
INSTRUCTIONS
============

The default sin-cos functions will cause math iterate compute, which is so slow and unsuitable for a MCU, many platform use `lookup table` and IQmath format to speed-up those math functions on MCU, especially  MCUs without  FPU.

**Comment by dmitry1945** [comment]
Hi @wanckl 

Yes, we will add them soon.

Thank you for idea.

Regards,
Dmitry

**Comment by dmitry1945** [comment]
@wanckl the support for sin/cos from LUT implemented in version 1.4.x

Thank you very much!
Dmitry
