### ISSUE TITLE
Meaning of divide by N  (DSP-94)

### ISSUE THREAD

**Issue by kurtwerbrouck** [espressif/esp-dsp#59]
Hello

I have 2 question on the next formule:

 y2_cf[i] = ((y_cf[i * 2 + 0] * y_cf[i * 2 + 0] + y_cf[i * 2 + 1] * y_cf[i * 2 + 1])/N);

What is the meaning of devide by N in above formule.

Why is there not sqrt() function ?

Thanks

**Comment by dmitry1945** [comment]
Hi @kurtwerbrouck ,

The result of FFT when you get sprectrum should be  divided by sqrt(N),
But we need 20*log10(abs(spectrum)), where 
abs(spectrum) = sqrt(real^2 + imag^2)/sqrt(N);

But, we can make so:
20*log10(abs(spectrum)) = 10*log10(abs(spectrum)^2) = 10*loag10((real^2 + imag^2)/N);

Regards,
Dmitry
