### ISSUE TITLE
Please update the esp-dsp on the package manager (DSP-96)

### ISSUE THREAD

**Issue by lijunru-hub** [espressif/esp-dsp#61]
The esp-dsp on the package manager is not the latest esp-dsp, and it does not compile on the idf.py master

**Comment by igrr** [comment]
@lijunru-hub do you mean esp-dsp?

**Comment by lijunru-hub** [comment]
YES

**Comment by dmitry1945** [comment]
Hi @lijunru-hub ,
Will do it today. 

Thank you
