### ISSUE TITLE
Extended Kalman Filter 计算速度  (DSP-105)

### ISSUE THREAD

**Issue by weilian1977** [espressif/esp-dsp#69]
Extended Kalman Filter 计算速度如何？

**Comment by dmitry1945** [comment]
Hi @weilian1977 the Process(...) for 13 states Kalman filetr on esp32 

takes about ~300k cycles. 

For the 13 states implementation the Process(...) takes about ~240k and the UpdateRefMeasurement(...)  takes about ~50k.

Regards,

Dmitry

**Comment by weilian1977** [comment]
300k cycles？300*1000/（240*1000000）~ =1.25ms？

**Comment by dmitry1945** [comment]
Hi @weilian1977 yes. It's about 1.25 mS on esp32. On esp32s3 it's faster, about 1.1 mS.

Regards,
Dmitry

**Comment by weilian1977** [comment]
Hi @dmitry1945， so cool！
