### ISSUE TITLE
Feature request: Optimized FIR with int32_t (DSP-68)

### ISSUE THREAD

**Issue by Patrik-Berglund** [espressif/esp-dsp#7]
Hi,

Would be great if you could make an optimized FIR filter for int32_t. 

Best Regards
Patrik Berglund

**Comment by Kameeno** [comment]
why not just convert into float ? 

float bufferConsumer::convert(const unsigned char *src, uint8_t index) {
  int i = src[0 + index] << 24 | src[1 + index] << 16 | src[2 + index] << 8;
  return i / (float)(INT_MAX - 256);
}


i take my 24bit data and i get directly a float 

for example:
 0x7FFFFF  = +1.0
 0x800000   =  -1.0
 0xC00000   =  - 0.5
 0x400000    =  + 0.5
