### ISSUE TITLE
ESP-IDF 5.1 Support? (DSP-110)

### ISSUE THREAD

**Issue by timsterc** [espressif/esp-dsp#72]
I'm getting a fair number of errors when trying to build w/ the esp-idf-5.1rc2.  Curious if there is a schedule for when esp-dsp will be updated to build w/ 5.1?

**Comment by dmitry1945** [comment]
Hi @timsterc 

Yes, it supports.

Are you able to build test_app or any esp-dsp example? 

Regards,
Dmitry

**Comment by timsterc** [comment]
Ah, my bad - I forgot that dsps_biquad_f32_aes3.S was missing and had added it in manually.  Is there a reason that was left out of the CMakeLists.txt ?

**Comment by dmitry1945** [comment]
@timsterc 

yes, the reason that this is a bug. Just forgot to include. We will fix it.

Thank you for the feedback.

Regards,
Dmitry

**Comment by timsterc** [comment]
@dmitry1945 - great, please let me know when it's updated.

**Comment by dmitry1945** [comment]
@timsterc  the fix is in master. Please pull.

Regards,
Dmitry

**Comment by timsterc** [comment]
@dmitry1945 - I'm using the - idf.py add-dependency "espressif/esp-dsp" - in my project - but it seems like it's still pulling the older CMakeLists.txt file?

**Comment by timsterc** [comment]
Changed my idf_component.yml file to specifically point to the git repo instead of using the component registry - that did the trick.

  espressif/esp-dsp:
    git: https://github.com/espressif/esp-dsp.git

**Comment by dmitry1945** [comment]
@timsterc yes.

Now the component manager files are up to date with lates changes.
It should work.

Thanks & best Regards,
Dmitry
