### ISSUE TITLE
Missing <cmath> header in modules/matrix/mat/mat.cpp

### ISSUE THREAD

**Issue by ftab** [espressif/esp-dsp#8]
## Environment

- Development Kit:      ESP32-LyraT
- IDF version v3.3
- Build System:         Make
- Compiler version 1.22.0-80-g6c4433a
- Operating System:     Windows and Linux
- Power Supply:         USB

## Problem Description

Unable to compile due to `abs is not a member of std` error. More details are available in the forums: https://esp32.com/viewtopic.php?f=20&t=12499

I will submit a PR shortly that resolves the issue on my copy

**Comment by igrr** [comment]
Fixed in https://github.com/espressif/esp-dsp/commit/06cb364c8af9dbed78d13e997d4c07800c031e76.
