### ISSUE TITLE
是否会支持esp-p4的芯片的指令 (DSP-132)

### ISSUE THREAD

**Issue by shenxiaozheng** [espressif/esp-dsp#82]
### Is your feature request related to a problem?

非常感谢esp-dsp库给开发者带来的便利，真的是一个伟大的工程，请问是否会对esp-p4芯片进行加速指令支持。

**Comment by dmitry1945** [comment]
Hi @shenxiaozheng ,

yes, sure. The esp-dsp will support esp32p4 optimization. Now we are working on it.

**Comment by shenxiaozheng** [comment]
Hi@dmitry1945 
Thank you very much for your help. We will do more development on this repository.
