### ISSUE TITLE
FIR for s16 (int16_t) type.  (DSP-138)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-dsp#86]
### Is your feature request related to a problem?

I found that the int16_t version of FIR filter only provide the one with decimation (fird)? If I want to use the normal FIR filter, do I have to convert it to float? Would there be performance penalty (I didn't see signed integer FIR in the benchmarks)?

**Comment by dmitry1945** [comment]
Hi @wuyuanyi135 

For fixed point you can use decimation value 1. In this case will be no decimation.
